# Continuous integration
name: $(Year:yy).2.$(date:yy)$(DayOfYear)$(rev:.rr)

trigger: none
pr:
- master

pool:
  name: Azure Pipelines
  vmImage: 'windows-latest'
  demands:
  - msbuild
  - visualstudio
  - vstest

stages:
- stage: Build
  jobs:
    - template: build.yml
      parameters:
        name: Release_Win32
        configuration: Release
        platform: Win32
    - template: build.yml
      parameters:
        name: Debug_Win32
        configuration: Debug
        platform: Win32
    - template: build.yml
      parameters:
        name: Release_Unicode_Win32
        configuration: Release Unicode
        platform: Win32
    - template: build.yml
      parameters:
        name: Debug_Unicode_Win32
        configuration: Debug Unicode
        platform: Win32
    - template: build.yml
      parameters:
        name: Release_x64
        configuration: Release
        platform: x64
    - template: build.yml
      parameters:
        name: Debug_x64
        configuration: Debug
        platform: x64
    - template: build.yml
      parameters:
        name: Release_Unicode_x64
        configuration: Release Unicode
        platform: x64
    - template: build.yml
      parameters:
        name: Debug_Unicode_x64
        configuration: Debug Unicode
        platform: x64

- stage: Release
  jobs:
    - template: release.yml
      parameters:
        name: ci
        sign: false
        title: Continuous Integration
        buildstatus: "[![Build Status](https://dev.azure.com/mrmapi/MFCMAPI/_apis/build/status/Continuous%20Integration/ci?branchName=master)](https://dev.azure.com/mrmapi/MFCMAPI/_build/latest?definitionId=14&branchName=master)"
        description: |-
          This is the unicode continuous integration build of MFCMAPI.

        prerelease: true