# This is a basic workflow to help you get started with Actions

name: Clang-format

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: clang-format (w/ diff)
        uses: egor-tensin/clang-format@v1
          # :-separated list of excluded files and directories
        with:
          exclude: include:mapistub
          
      - name: clang-tidy check
        uses: muxee/clang-tidy-action@0.0.1-rc1
        
      - name: Scan headers
        run: for /r %%g in (*.h) do "%VCINSTALLDIR%\Tools\Llvm\bin\clang-format.exe" -i %%g

      - name: Scan cpp
        run: for /r %%g in (*.cpp) do "%VCINSTALLDIR%\Tools\Llvm\bin\clang-format.exe" -i %%g

