name: Clang-format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  check-formatting:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: clang-format (w/ diff)
        uses: egor-tensin/clang-format@v1
        with:
          # :-separated list of excluded files and directories
          exclude: include:mapistub
